# Generated by Django 4.0.3 on 2022-03-13 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(default=0)),
                ('attrition', models.CharField(max_length=3)),
                ('business_travel', models.CharField(max_length=100)),
                ('daily_rate', models.IntegerField()),
                ('department', models.CharField(max_length=100)),
                ('distance_from_home', models.DecimalField(decimal_places=2, max_digits=10)),
                ('education', models.IntegerField()),
                ('education_field', models.CharField(max_length=100)),
                ('employee_count', models.IntegerField()),
                ('employee_number', models.IntegerField()),
                ('environment_satisfaction', models.IntegerField()),
                ('gender', models.CharField(max_length=100)),
                ('hourly_rate', models.IntegerField()),
                ('job_involvement', models.IntegerField()),
                ('job_level', models.IntegerField()),
                ('job_role', models.CharField(max_length=100)),
                ('job_satisfaction', models.IntegerField()),
                ('marital_status', models.CharField(max_length=100)),
                ('monthly_income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monthly_rate', models.IntegerField()),
                ('num_companies_worked', models.IntegerField()),
                ('is_over_18', models.CharField(max_length=1)),
                ('over_time', models.CharField(max_length=100)),
                ('percent_salary_hike', models.IntegerField()),
                ('performance_rating', models.IntegerField()),
                ('relationship_satisfaction', models.IntegerField()),
                ('standard_hours', models.IntegerField()),
                ('stock_option_level', models.IntegerField()),
                ('total_working_years', models.IntegerField()),
                ('training_time_last_year', models.IntegerField()),
                ('work_life_balance', models.IntegerField()),
                ('years_at_company', models.IntegerField()),
                ('years_in_current_role', models.IntegerField()),
                ('years_since_last_promotion', models.IntegerField()),
                ('years_with_current_manager', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('importance', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_people', models.IntegerField()),
                ('age', models.DecimalField(decimal_places=2, max_digits=10)),
                ('distance_from_home', models.DecimalField(decimal_places=2, max_digits=10)),
                ('job_level', models.DecimalField(decimal_places=2, max_digits=10)),
                ('job_satisfaction', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monthly_income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('performance_rating', models.DecimalField(decimal_places=2, max_digits=10)),
                ('percent_salary_hike', models.DecimalField(decimal_places=2, max_digits=10)),
                ('relationship_satisfaction', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_working_years', models.DecimalField(decimal_places=2, max_digits=10)),
                ('work_life_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('years_in_current_role', models.DecimalField(decimal_places=2, max_digits=10)),
                ('years_at_company', models.DecimalField(decimal_places=2, max_digits=10)),
                ('years_with_current_manager', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
